name: "Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
      options: >-
        --entrypoint /bin/sh
        -c "pip install -q uv && exec \"$@\""

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: init depandency
        run: uv sync

      - name: execute "main"
        run: uv run main.py